### ISSUE TITLE
[BUG] hiding header or footer does not extend workspace view appropriately

### ISSUE THREAD

**Issue by Byolock** [Lissy93/dashy#522]
### Environment

Self-Hosted (Docker)

### Version

2.0.3

### Describe the problem

Hiding the footer or header does not lead to the iframe of the selected app extending into the free space, instead the background of the selected theme is visible.

Steps to reproduce

1. add
```
   "hideComponents": {
      "hideSearch": true,
      "hideHeading": true,
      "hideNav": true,
      "hideSettings": true,
      "hideFooter": true
    },
```
to your configuration
2. apply configuration
3. switch to workspace view
4. select any app

Tested with Firefox and Brave Browser.
Probably also relates is the fact that hiding header and not footer leads to the footer not beeing at the bottom of the site.
I attached screenshots for both problems.

### Additional info

[Background Image from the Adventure theme can be seen below the iframe]
<img width="1918" alt="dashy" src="https://user-images.githubusercontent.com/25748003/156391918-60f3af5c-8b70-4d76-b1e0-289a6019ecbd.png">

[Footer is floating if hiding header]
<img width="1919" alt="dashy2" src="https://user-images.githubusercontent.com/25748003/156393648-505b7b90-70c5-4257-994d-90efc9699fd6.png">

### Please tick the boxes

- [X] You are using a [supported](https://github.com/Lissy93/dashy/blob/master/.github/SECURITY.md#supported-versions) version of Dashy (check the first two digits of the version number)
- [x] You've checked that this [issue hasn't already been raised](https://github.com/Lissy93/dashy/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://github.com/Lissy93/dashy/tree/master/docs#readme) and [troubleshooting](https://github.com/Lissy93/dashy/blob/master/docs/troubleshooting.md#troubleshooting) guide
- [X] You agree to the [code of conduct](https://github.com/Lissy93/dashy/blob/master/.github/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct)

**Comment by Lissy93** [comment]
Heya @Byolock
Thanks for the bug repot, and apologies for the delay in implementing this.
It should now be fixed in #557 / 2.0.6 
Feel free to reach out if you need anything else :)

If you are using a custom theme, and experience a similar issue in the future, then you can adjust the `--footer-height` CSS variable

**Comment by Byolock** [comment]
@Lissy93 No worries for the delay. Thanks for the change, however it seems to not fully fix my issue. The footer is now at the bottom but the iframe does still not extend all the way to the bottom of the window : 
<img width="1078" alt="dashy-workspace" src="https://user-images.githubusercontent.com/25748003/160424611-dfecff6a-956c-4b87-82e6-5118b5c1753a.png">

I tried to change `--foother-height` that didn't do anything, but im also not sure which value would be right. Tried to change from 128px to 64px and then to 256px and didn't see any visual difference.

**Comment by Lissy93** [comment]
/keep-open

This issue isn't resolved. I think I need to approach it differently to get the solution

**Comment by Byolock** [comment]
@Lissy93 Maybe this is something that raises some new ideas ?

I finally had some time trying different css changes to see if I would get the the iframe to fit properly. I set the height of the iframe to `calc(100% - var(--header-height) + var(--footer-height))`. That change made the iframe fit nearly correctly (it is a few pixels to high but barely noticable). header-height value is 6.3rem footer-height value is 4rem. My guess is this is nearly working by pure chance or does that make any sense to you?

Using `calc(100% - var(--footer-height))` uses more space than the default `calc(100% - var(--header-height)` but still misses a fair bit of space.

I did wonder, I have "hide header" enabled in the configuration, so why is the header height necessary to determine the height of the IFrame in the first place?

Some further experimenting got me to the idea that `calc(100% - var(--footer-height))` is probably correct and the missing space is because I can still see a small header even though I disabled it in the configuration. The header class has a padding property of `0.5rem`. A look on the footer class revealed a padding of `0.25rem`. That got me to 0.75rem, so I changed the Iframe height to : `calc(100% - var(--footer-height) + 0.75rem)`. That wasn't correct either but it was obvious this change used up exactly half of the remaining space which should be used by the iFrame, so I changed it to `calc(100% - var(--footer-height) + 1.5rem)`. 
This change made the iFrame now exactly as high as it should be. The interresting thing is, `1.5rem` is exactly the margin-top property of the footer class. So maybe the correct solution to this problem is to take '100% height minus the height of the footer without its margin-top property' for the height of the IFrame?

My understanding of CSS and the terminology is very limeted so I hope what i've written makes any sense.

**Comment by CrazyWolf13** [comment]
#1463 Seems related

**Comment by alanmilinovic** [comment]
I my case this is not fixed.

**Comment by TheAzureWizard** [comment]
This is not fixed.
Brand new docker container, never used Dashy before.
Great app, working well except this bug.

It seems that the height of the extra space at the bottom is proportional to the number of hidden items.
i.e. it's larger when 'hide header' is selected.

With 'Hide Header'
<img width="1918" height="943" alt="Image" src="https://github.com/user-attachments/assets/7f98699f-96f5-4a3b-8651-d760dd0008c6" />

with nothing hidden (still some space missing)
<img width="1917" height="881" alt="Image" src="https://github.com/user-attachments/assets/19a29de1-c7c1-4a7a-a8ae-27a5bc649804" />

Options showing nothing hidden:
<img width="912" height="269" alt="Image" src="https://github.com/user-attachments/assets/9f674b71-a3cc-43b1-afda-2204e6da1b33" />

**Comment by lissy93** [comment]
Sorry about that, lemme re-open
I'm gonna totally re-do a lot of the workspace view when I come to fixing #2172, so will cover this off at the same time. 

Thank you for the screenshots @TheAzureWizard - that's really helpful
